---
document: feedback-pipeline-compose-view
version: 1
data:
  name: Automotive Minimum Package View
  description: A view of minimum set common to all workloads
  maintainer: ssmoogen
  labels:
  - automotive-c9s-env
  repository: automotive-c9s-repositories
