---
document: feedback-pipeline-compose-view
version: 1
data:
  name: Automotive B-Team Combined Package View using CentOS Stream 8
  description: A feature list trying to combine all standard workloads
  maintainer: ssmoogen
  labels:
  - automotive-base-c8s-all
  repository: automotive-base-c8s-repositories
