---
document: feedback-pipeline-compose-view
version: 1
data:
  name: Automotive B-Team dnf Package View using CentOS Stream 9
  description: A view of dnf packages added to minimal environment
  maintainer: ssmoogen
  labels:
  - automotive-base-c9s-dnf
  repository: automotive-base-c9s-repositories
