---
document: feedback-pipeline-compose-view
version: 1
data:
  name: Automotive A-Team Package View using CentOS Stream 9
  description: A view of packages which can be used by toolchain group
  maintainer: ssmoogen
  labels:
  - automotive-toolchain-c9s
  repository: automotive-toolchain-c9s-repositories
