---
document: feedback-pipeline-compose-view
version: 1
data:
  name: Automotive B-Team Bootloader Package View using CentOS Stream 8
  description: A view of set for grub2 boot
  maintainer: ssmoogen
  labels:
  - automotive-base-c8s-bootloader-grub2
  repository: automotive-base-c8s-repositories
