---
document: feedback-pipeline-compose-view
version: 1
data:
  name: Automotive Runtime Package View
  description: A view of set for a runtime environment
  maintainer: ssmoogen
  labels:
  - automotive-c9s-ostree
  - automotive-c9s-podman
  repository: automotive-c9s-repositories
