---
document: feedback-pipeline-compose-view
version: 1
data:
  name: Automotive B-Team DNF Package View using CentOS Stream 8
  description: A view of dnf packages added to minimal environment
  maintainer: ssmoogen
  labels:
  - automotive-base-c8s-dnf
  repository: automotive-base-c8s-repositories
