---
document: feedback-pipeline-compose-view
version: 1
data:
  name: Automotive Minimal Package View using CentOS Stream 8
  description: A view of set for ostree
  maintainer: ssmoogen
  labels:
  - automotive-base-c8s-dnf
  repository: automotive-base-c8s-repositories
