---
document: feedback-pipeline-compose-view
version: 1
data:
  name: Automotive B-Team Minimal Package View using CentOS Stream 9
  description: A view of minimal set common to all workloads
  maintainer: ssmoogen
  labels:
  - automotive-base-c9s-minimal
  repository: automotive-base-c9s-repositories
