---
data:
  description: Automotive CentOS image manifest packages.
  labels:
  - automotive-c8s
  maintainer: rajeshsriva
  repositories:
  - repository-c8s
  name: Automotive CentOS image manifest packages
  packages:
  - ModemManager
  - ModemManager-glib
  - NetworkManager
  - NetworkManager-libnm
  - NetworkManager-wifi
  - NetworkManager-wwan
  - acl
  - attr
  - audit
  - audit-libs
  - basesystem
  - bash
  - bash-completion
  - bind-export-libs
  - brotli
  - bubblewrap
  - bzip2-libs
  - ca-certificates
  - checkpolicy
  - chkconfig
  - chrony
  - clevis
  - clevis-dracut
  - clevis-luks
  - clevis-systemd
  - conmon
  - container-selinux
  - containernetworking-plugins
  - containers-common
  - coreutils
  - coreutils-common
  - cpio
  - cracklib
  - cracklib-dicts
  - crda
  - criu
  - crypto-policies
  - crypto-policies-scripts
  - cryptsetup
  - cryptsetup-libs
  - curl
  - cyrus-sasl-lib
  - dbus
  - dbus-common
  - dbus-daemon
  - dbus-glib
  - dbus-libs
  - dbus-tools
  - device-mapper
  - device-mapper-event
  - device-mapper-event-libs
  - device-mapper-libs
  - device-mapper-persistent-data
  - dhcp-client
  - dhcp-common
  - dhcp-libs
  - diffutils
  - dnsmasq
  - dosfstools
  - dracut
  - dracut-config-generic
  - dracut-network
  - e2fsprogs
  - e2fsprogs-libs
  - efi-filesystem
  - efibootmgr
  - efivar-libs
  - elfutils-debuginfod-client
  - elfutils-default-yama-scope
  - elfutils-libelf
  - elfutils-libs
  - expat
  - file
  - file-libs
  - filesystem
  - findutils
  - firewalld
  - firewalld-filesystem
  - freetype
  - fuse
  - fuse-common
  - fuse-libs
  - fuse-overlayfs
  - fuse3
  - fuse3-libs
  - fwupd
  - gawk
  - gdbm
  - gdbm-libs
  - gdisk
  - geolite2-city
  - geolite2-country
  - gettext
  - gettext-libs
  - glib2
  - glibc
  - glibc-common
  - glibc-minimal-langpack
  - gmp
  - gnupg2
  - gnupg2-smime
  - gnutls
  - gobject-introspection
  - gpgme
  - greenboot
  - greenboot-grub2
  - greenboot-reboot
  - greenboot-rpm-ostree-grub2
  - greenboot-status
  - grep
  - grub2-common
  - grub2-efi-x64
  - grub2-pc
  - grub2-pc-modules
  - grub2-tools
  - grub2-tools-extra
  - grub2-tools-minimal
  - grubby
  - gzip
  - hardlink
  - hostname
  - hwdata
  - ima-evm-utils
  - info
  - initscripts
  - ipcalc
  - iproute
  - ipset
  - ipset-libs
  - iptables
  - iptables-ebtables
  - iptables-libs
  - iputils
  - iw
  - iwl100-firmware
  - iwl1000-firmware
  - iwl105-firmware
  - iwl135-firmware
  - iwl2000-firmware
  - iwl2030-firmware
  - iwl3160-firmware
  - iwl5000-firmware
  - iwl5150-firmware
  - iwl6000-firmware
  - iwl6050-firmware
  - iwl7260-firmware
  - jansson
  - jose
  - jq
  - json-c
  - json-glib
  - kbd
  - kbd-legacy
  - kbd-misc
  - kernel
  - kernel-core
  - kernel-modules
  - keyutils
  - keyutils-libs
  - kmod
  - kmod-libs
  - kpartx
  - krb5-libs
  - less
  - libacl
  - libaio
  - libarchive
  - libassuan
  - libatasmart
  - libattr
  - libblkid
  - libblockdev
  - libblockdev-crypto
  - libblockdev-fs
  - libblockdev-loop
  - libblockdev-mdraid
  - libblockdev-part
  - libblockdev-swap
  - libblockdev-utils
  - libbytesize
  - libcap
  - libcap-ng
  - libcom_err
  - libcroco
  - libcurl
  - libdb
  - libdb-utils
  - libedit
  - libevent
  - libfdisk
  - libffi
  - libgcab1
  - libgcc
  - libgcrypt
  - libgomp
  - libgpg-error
  - libgudev
  - libgusb
  - libibverbs
  - libidn2
  - libjose
  - libkcapi
  - libkcapi-hmaccalc
  - libksba
  - libluksmeta
  - libmaxminddb
  - libmbim
  - libmbim-utils
  - libmetalink
  - libmnl
  - libmodulemd
  - libmount
  - libndp
  - libnet
  - libnetfilter_conntrack
  - libnfnetlink
  - libnftnl
  - libnghttp2
  - libnl3
  - libnsl2
  - libpcap
  - libpkgconf
  - libpng
  - libpsl
  - libpwquality
  - libqb
  - libqmi
  - libqmi-utils
  - librepo
  - libreport-filesystem
  - libseccomp
  - libsecret
  - libselinux
  - libselinux-utils
  - libsemanage
  - libsepol
  - libsigsegv
  - libslirp
  - libsmartcols
  - libsmbios
  - libsolv
  - libss
  - libssh
  - libssh-config
  - libstdc++
  - libtasn1
  - libtirpc
  - libudisks2
  - libunistring
  - libusbx
  - libuser
  - libutempter
  - libuuid
  - libverto
  - libxcrypt
  - libxkbcommon
  - libxml2
  - libxmlb
  - libyaml
  - libzstd
  - linux-firmware
  - lua-libs
  - luksmeta
  - lvm2
  - lvm2-libs
  - lz4-libs
  - mdadm
  - memstrack
  - microcode_ctl
  - mokutil
  - mozjs60
  - mpfr
  - ncurses
  - ncurses-base
  - ncurses-libs
  - nettle
  - nftables
  - nmap-ncat
  - npth
  - nspr
  - nss
  - nss-altfiles
  - nss-softokn
  - nss-softokn-freebl
  - nss-sysinit
  - nss-util
  - oniguruma
  - openldap
  - openssh
  - openssh-clients
  - openssh-server
  - openssl
  - openssl-libs
  - openssl-pkcs11
  - os-prober
  - ostree
  - ostree-libs
  - p11-kit
  - p11-kit-trust
  - pam
  - parted
  - passwd
  - pciutils
  - pciutils-libs
  - pcre
  - pcre2
  - pigz
  - pinentry
  - pkgconf
  - pkgconf-m4
  - pkgconf-pkg-config
  - platform-python
  - platform-python-pip
  - platform-python-setuptools
  - podman
  - podman-catatonit
  - policycoreutils
  - policycoreutils-python-utils
  - polkit
  - polkit-libs
  - polkit-pkla-compat
  - popt
  - procps-ng
  - protobuf
  - protobuf-c
  - publicsuffix-list-dafsa
  - python3-audit
  - python3-dbus
  - python3-decorator
  - python3-firewall
  - python3-gobject-base
  - python3-libs
  - python3-libselinux
  - python3-libsemanage
  - python3-nftables
  - python3-pip-wheel
  - python3-policycoreutils
  - python3-setools
  - python3-setuptools-wheel
  - python3-six
  - python3-slip
  - python3-slip-dbus
  - rdma-core
  - readline
  - redhat-release
  - redhat-release-eula
  - rootfiles
  - rpm
  - rpm-libs
  - rpm-ostree
  - rpm-ostree-libs
  - rpm-plugin-selinux
  - rsync
  - runc
  - sed
  - selinux-policy
  - selinux-policy-targeted
  - setools-console
  - setup
  - shadow-utils
  - shared-mime-info
  - shim-x64
  - skopeo
  - slirp4netns
  - sqlite-libs
  - sudo
  - systemd
  - systemd-libs
  - systemd-pam
  - systemd-udev
  - tar
  - timedatex
  - tmux
  - tpm2-tools
  - tpm2-tss
  - traceroute
  - trousers
  - trousers-lib
  - tzdata
  - udisks2
  - usbguard
  - usbguard-selinux
  - util-linux
  - vim-minimal
  - volume_key-libs
  - which
  - wpa_supplicant
  - xfsprogs
  - xkeyboard-config
  - xz
  - xz-libs
  - zlib
document: feedback-pipeline-workload
version: 1
 - 
