---
# This configuration file defines an "Environment" in Feedback Pipeline.
# https://tiny.distro.builders
#
# Environments influence how a workload looks like when installed.
# That's achieved by including specific packages — like coreutils-single — that
# influence the result.
# Environments can also act as base images when monitoring container sizes.

document: feedback-pipeline-environment
version: 1
data:
  # id is the filename — that automatically prevents collisions for free!

  ### MANDATORY FIELDS ###
  
  # Name is an identifier for humans
  #
  # (mandatory field)
  name: Automotive SIG working environment using CentOS Stream 9 for the toolchain
  
  # A short description, perhaps hinting the purpose
  #
  # (mandatory field)
  description: Automotive SIG working environment using CentOS Stream 9 for the toolchain

  # Who maintains it? This is just a freeform string
  # for humans to read. In Fedora, a FAS nick is recommended.
  #
  # (mandatory field)
  maintainer: ssmoogen

  # Different instances of the environment, one per repository.
  #
  # (mandatory field)
  repositories:
  - automotive-toolchain-c9s-repositories

  # Packages defining this environment.
  # This list includes packages for all
  # architectures — that's the one to use by default.
  #
  # (mandatory field)
  packages:
  # Base leaf packages with all systems.
  - NetworkManager
  - audit
  - chrony
  - dhcp-client
  - dracut-config-generic
  - e2fsprogs
  - efibootmgr
  - glibc-langpack-en
  - hostname
  - kernel
  - kernel-tools
  - passwd
  - rng-tools
  - rootfiles
  - rsyslog
  - selinux-policy-targeted
  - systemd-udev
  # dnf
  - microdnf
  # ostree
  - greenboot-reboot
  - greenboot-status
  - nss-altfiles
  # podman
  - podman
  # flatpak
  - flatpak
  # qemu
  - qemu-kvm
  - libvirt-client
  # qa-test workload
  - openssh-server
  - openssh-clients
  - dhcp-server
  - sudo
  - yum
  # qt5 applications possibly needed for infotainment
  - qt5-qtbase
  - qt5-qtwayland
  - qt5-qtx11extras
  - qt5-qtmultimedia
  - qt5-qtquickcontrols
  - qt5-qtquickcontrols2
  - qt5-qtsensors
  - qt5-qttools
  - qt5-qtimageformats
  - qt5-qtgraphicaleffects
  - libwayland-client
  - libwayland-server

  # Labels connect things together.
  # Workloads get installed in environments with the same label.
  # They also get included in views with the same label.
  # 
  # (mandatory field)
  labels:
  - automotive-toolchain-c9s

  ### OPTIONAL FIELDS ###

  # Architecture-specific packages.
  #
  # (optional field)
  arch_packages:
    x86_64:
    - shim-x64
    - microcode_ctl
    - grub2-efi-x86
    - grub2-pc
    - grub2-pc-modules
    aarch64:
    - shim-aa64
    - tianocore-rpi4-uefi
    - grub2-efi-aa64

  # Extra installation options.
  # The following are now supported:
  # - "include-docs" - include documentation packages
  # - "include-weak-deps" - automatically pull in "recommends" weak dependencies
  #
  # (optional field)
  options:
  - exclude-docs
  - exclude-weak-deps

