---
document: feedback-pipeline-compose-view
version: 1
data:
  name: Automotive B-Team Servers Package View using CentOS Stream 9
  description: Packages which add services that might be only used for small usecases
  maintainer: ssmoogen
  labels:
  - automotive-base-c9s-servers
  repository: automotive-base-c9s-repositories
