---
document: feedback-pipeline-compose-view
version: 1
data:
  name: Automotive Minimal Package View using CentOS Stream 9
  description: A view of set for grub2 boot
  maintainer: ssmoogen
  labels:
  - automotive-base-c9s-bootloader-grub2
  repository: automotive-base-c9s-repositories
