---
document: feedback-pipeline-workload
version: 1
data:
  name: Automotive off-vehicle package set
  description: >
    The set of packages representing the automotive extra, off-vehicle
    content.  This workload builds on top of the in-vehicle content and
    extends it with various development tools.
  # Contacts: psabata, ssmoogen
  maintainer: automotive-base-enablement
  labels:
    - automotive
  options:
    - include-docs
  packages:
    - acl
    - bc
    - binutils
    - bison
    - bzip2
    - chrony
    - cmake
    - cpio
    - curl
    - dhcp-client
    - diffutils
    - dnf
    - dosfstools
    - dwarves
    - elfutils-devel
    - emacs-nox
    - findutils
    - flex
    - gawk
    - gawk-all-langpacks
    - gdb
    - gcc
    - gcc-c++
    - gcc-plugin-devel
    - git
    - glibc-gconv-extra
    - hmaccalc
    - inih
    - jq
    - kpartx
    - libedit
    - libxcrypt-compat
    - libxmlb
    - m4
    - make
    - memstrack
    - mtools
    - nano
    - ncurses-devel
    - net-tools
    - openssh-clients
    - openssh-server
    - openssl-pkcs11
    - patch
    - perl-Carp
    - perl-devel
    - perl-interpreter
    - pigz
    - pkgconf
    - polkit
    - python3
    - python3-devel
    - python3-iniparse
    - python3-libs
    - python3-pip-wheel
    - python3-setuptools-wheel
    - python-unversioned-command
    - qemu-img
    - redhat-rpm-config
    - rng-tools
    - rootfiles
    - rpm-build
    - sed
    - skopeo
    - strace
    - sudo
    - tar
    - vim-enhanced
    - wget
    - xfsprogs
    - xz
    - yum
    - zstd
