---
document: feedback-pipeline-compose-view
version: 1
data:
  name: Automotive Qemu+Podman Package View using CentOS Stream 9
  description: A combined view of Qemu and Podman package sets
  maintainer: ssmoogen
  labels:
  - automotive-base-c9s-qemu_podman
  repository: automotive-base-c9s-repositories
