---
document: feedback-pipeline-compose-view
version: 1
data:
  name: Automotive Neptune Package View
  description: A view looking at just the Neptune Sample application
  maintainer: ssmoogen
  labels:
  - automotive-c9s-neptune
  repository: automotive-c9s-repositories
