---
document: feedback-pipeline-compose-view
version: 1
data:
  name: Automotive B-Team Neptune Package View for CentOS Stream 9
  description: A view looking at just the Neptune Sample application
  maintainer: ssmoogen
  labels:
  - automotive-base-c9s-neptune
  repository: automotive-base-c9s-repositories
