---
document: feedback-pipeline-compose-view
version: 1
data:
  name: Automotive Development Package View
  description: Packages which are needed to build the kernel package for a generic automotive BSP
  maintainer: ssmoogen
  labels:
  - automotive-c9s-development
  repository: automotive-c9s-repositories
