---
document: feedback-pipeline-compose-view
version: 1
data:
  name: Automotive B-Team Podman Package View using CentOS Stream 8
  description: Packages that get pulled in when using just podman
  maintainer: ssmoogen
  labels:
  - automotive-base-c8s-podman
  repository: automotive-base-c8s-repositories
