---
document: feedback-pipeline-compose-view
version: 1
data:
  name: Automotive Infotainment Minimum Package View
  description: A view of set for a infotainment minimum environment
  maintainer: rmajadas
  labels:
  - automotive-c9s-infotainment-minimum
  repository: automotive-c9s-repositories
