---
# This configuration file defines a "Workload" in Feedback Pipeline.
# https://tiny.distro.builders
#
# Workload is a set of packages with a purpouse that someone cares about.
# They might want to monitor it for the install size, dependencies that get
# pulled in, etc.

document: feedback-pipeline-workload
version: 1
data:
  # id is the filename — that automatically prevents collisions for free!


  ### MANDATORY FIELDS ###
  
  # Name is an identifier for humans
  #
  # (mandatory field)
  name: Automotive B-Team ostree Workload using CentOS Stream 9

  # A short description, perhaps hinting the purpose
  #
  # (mandatory field)
  description: ostree Workload for Automotive CentOS Stream 9 EPEL

  # Who maintains it? This is just a freeform string
  # for humans to read. In Fedora, a FAS nick is recommended.
  #
  # (mandatory field)
  maintainer: ssmoogen

  # Labels connect things together.
  # Workloads get installed in environments with the same label.
  # They also get included in views with the same label.
  # 
  # (mandatory field)
  labels:
  - automotive-base-c9s-all
  - automotive-base-c9s-ostree

  # Repositories tell you what ones to resolve against.
  # 
  # (mandatory field)
  repositories:
  - automotive-base-c9s-repositories

  # Packages defining this workload.
  # This list includes packages for all
  # architectures — that's the one to use by default.
  #
  # (mandatory field)
  packages:
  - greenboot-reboot
  - greenboot-status
  - nss-altfiles

  ### OPTIONAL FIELDS ###

  # Architecture-specific packages.
  #
  # (optional field)
  #arch_packages:
  #  x86_64:
  #  - arch-specific-package

  # Extra installation options.
  # The following are now supported:
  # - "include-docs" - include documentation packages
  # - "include-weak-deps" - automatically pull in "recommends" weak dependencies
  #
  # (optional field)
  #options:
  #- option
