document: feedback-pipeline-workload
version: 1
data:
  name: qt6 eln-extra packages
  description: QT6 ELN Extras packages
  maintainer: tdawson

  packages:
  - qt6-rpm-macros
  - qt6-srpm-macros
  - qt6-qt3d
  - qt6-qt5compat
  - qt6-qtbase
  - qt6-qtcharts
  - qt6-qtconnectivity
  - qt6-qtdatavis3d
  - qt6-qtdeclarative
  - qt6-qtimageformats
  - qt6-qtlottie
  - qt6-qtmultimedia
  - qt6-qtnetworkauth
  - qt6-qtpositioning
  - qt6-qtquick3d
  - qt6-qtquicktimeline
  - qt6-qtremoteobjects
  - qt6-qtscxml
  - qt6-qtsensors
  - qt6-qtserialbus
  - qt6-qtserialport
  - qt6-qtshadertools
  - qt6-qtsvg
  - qt6-qttools
  - qt6-qttranslations
  - qt6-qtvirtualkeyboard
  - qt6-qtwayland
  - qt6-qtwebchannel
  - qt6-qtwebsockets

  labels:
  - eln-extras

  arch_packages:
    aarch64:
    - qt6ct
    ppc64le:
    - qt6ct
    x86_64:
    - qt6ct
