---
document: feedback-pipeline-repository
version: 2
data:
  name: CentOS Stream for el8
  description: CentOS Stream BaseOS, AppStream dna extras; for el8
  maintainer: james
  source:

    repos:

      stream-baseos:
        baseurl: http://mirror.centos.org/centos/8-stream/BaseOS/$basearch/os/
        priority: 1
      
      stream-appstream:
        baseurl: http://mirror.centos.org/centos/8-stream/AppStream/$basearch/os/
        priority: 2
      
      stream-extras:
        baseurl: http://mirror.centos.org/centos/8-stream/extras/$basearch/os/
      
    releasever: "8-stream"
    
    architectures:
    - aarch64
    #- ppc64le
    #- s390x
    - x86_64

