---
document: feedback-pipeline-repository
version: 2
data:
  name: Fedora ELN (backed by rawhide)
  description: Fedora ELN with rawhide as a backup for missing packages
  maintainer: asamalik
  source:

    repos:

      rawhide-everything:
        baseurl: https://kojipkgs.fedoraproject.org/compose/rawhide/latest-Fedora-Rawhide/compose/Everything/$basearch/os/
        koji_api_url: https://koji.fedoraproject.org/kojihub
        koji_files_url: https://kojipkgs.fedoraproject.org
      
      eln-everything:
        baseurl: https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/Everything/$basearch/os/
        priority: 1
        koji_api_url: https://koji.fedoraproject.org/kojihub
        koji_files_url: https://kojipkgs.fedoraproject.org
      
      eln-appstream:
        baseurl: https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/AppStream/$basearch/os/
        priority: 2
        koji_api_url: https://koji.fedoraproject.org/kojihub
        koji_files_url: https://kojipkgs.fedoraproject.org

    releasever: "rawhide"
    
    architectures:
    - aarch64
    - ppc64le
    - s390x
    - x86_64

    composeinfo: https://odcs.fedoraproject.org/composes/production/latest-Fedora-ELN/compose/metadata/composeinfo.json

    base_buildroot_override: ['bash', 'bzip2', 'coreutils', 'cpio', 'diffutils', 'findutils', 'gawk', 'glibc-minimal-langpack', 'grep', 'gzip', 'info', 'make', 'patch', 'redhat-rpm-config', 'rpm-build', 'sed', 'shadow-utils', 'tar', 'unzip', 'util-linux', 'which', 'xz']