document: feedback-pipeline-workload
version: 1
data:
  name: Totem
  description: Default video player in Workstation
  maintainer: sst_desktop

  packages:
  - clutter
  - clutter-gtk
  - clutter-gst3
  - cogl
  - totem
  - totem-video-thumbnailer

  labels:
  - eln
  - c9s
