document: feedback-pipeline-workload
version: 1
data:
  name: ltrace
  description: Developer tooling to track runtime library calls.
  maintainer: sst_platform_tools

  packages:
  - ltrace

  labels:
  - eln
  - c9s
