document: feedback-pipeline-workload
version: 1
data:
  name: Apache Maven
  description: Java project management and project comprehension tool
  maintainer: sst_cs_apps

  packages:
  - maven
  # XXX runtime or build deps of Maven that are not automatically added
  # to be eventually removed
  - javapackages-bootstrap
  - maven-verifier
  - sonatype-oss-parent
  - javamail
  - log4j12

  labels:
  - c9s
