document: feedback-pipeline-workload
version: 1
data:
  name: GTK 3 toolkit
  description: Software toolkit for developing applications
  maintainer: sst_desktop

  packages:
  - gtk3

  labels:
  - eln
  - c9s
