document: feedback-pipeline-workload
version: 1
data:
  name: Python additions (ACG4)
  description: Less important packages from the Python interpreter bundle, provided without strict compatibility guarantees (ACG4)
  maintainer: sst_cs_apps

  packages:
  - python3-idle
  - python3-tkinter

  labels:
  - eln
  - c9s
