document: feedback-pipeline-workload
version: 1
data:
  name: grubby
  description: Command line tool for updating BootLoaderSpec files
  maintainer: sst_desktop

  packages:
  - grubby

  labels:
  - eln
  - c9s
