document: feedback-pipeline-workload
version: 1
data:
  name: CPU microcode tools
  description: Tools to update CPU microcode
  maintainer: sst_kernel_tps

  arch_packages:
    x86_64:
    - microcode_ctl

  labels:
  - eln
  - c9s
