document: feedback-pipeline-workload
version: 1
data:
  name: IdM Smart Cards
  description: Specific packages for client-side smart card enablement on RHEL.
  maintainer: sst_identity_management

  packages:
  - esc

  labels:
  - eln
  - c9s
