document: feedback-pipeline-workload
version: 1
data:
  name: FreeIPA Client - Samba domain member
  description: Samba domain member on FreeIPA client
  maintainer: sst_identity_management

  packages:
  - ipa-client
  - ipa-client-samba
  - ipa-selinux # rich dependency that is otherwise unmet

  labels:
  - eln
  - c9s
