document: feedback-pipeline-workload
version: 1
data:
  name: composer-cli weldr client
  description: composer-cli command line utility to control osbuild-composer
  maintainer: sst_front_door
  labels:
    - eln
    - c9s

  packages:
    - weldr-client
