document: feedback-pipeline-workload
version: 1
data:
  name: Gedit
  description: Text editor for Workstation
  maintainer: sst_desktop

  packages:
  - gedit
  - gedit-plugins

  labels:
  - eln
  - c9s
