document:  feedback-pipeline-workload
version: 1
data:
    name: kernel devel/debug
    description: Kernel packages used for devel/debug
    maintainer: sst_kernel_maintainers
    packages:
        - kernel-cross-headers
        - kernel-headers
        - kernel-devel
    labels:
        - eln
        - c9s
    arch_packages:
        x86_64:
            - kernel-tools-libs-devel
        aarch64:
            - kernel-tools-libs-devel
        ppc64le:
            - kernel-tools-libs-devel
        s390x:
            - kernel-zfcpdump-devel

