document: feedback-pipeline-workload
version: 1
data:
  name: Debuggers
  description: Debuggers and components
  maintainer: sst_platform_tools

  packages:
  - gdb
  - gdb-doc
  - gdb-gdbserver
  - gdb-headless
  - libbabeltrace
  - libbabeltrace-devel
  - source-highlight
  # See libipt below

  labels:
  - eln
  - c9s

  # libipt is Intel only
  arch_packages:
    i686:
    - libipt
    - libipt-devel
    x86_64:
    - libipt
    - libipt-devel
