document: feedback-pipeline-workload
version: 1
data:
  name: Audio playback
  description: Libraries and daemons for audio playback
  maintainer: sst_graphics_infrastructure

  packages:
    - pulseaudio
    - libcanberra
    - openal-soft
    - pavucontrol

  labels:
    - eln
    - c9s
