document: feedback-pipeline-unwanted
version: 1
data:
  name: Unwanted Packages -- sst_front_door
  description: Packages that should not be distributed in RHEL 9
  maintainer: sst_front_door
  labels:
    - eln
    - c9s

  unwanted_packages:
    # mpitt: only needed for integration tests (buildroot), never ship this
    - cockpit-tests

    # mpitt: Will be deprecated soon, let's not introduce it
    - cockpit-dashboard

    # Radek Vykydal:
    # system-config-kickstart has been deprecated upstream, it has not
    # been ported to Python 3, and shouldn't have been included in RHEL 8.
    - system-config-kickstart

    # Vendula Poncova: python3-pydbus has been replaced by python3-dasbus
    - python3-pydbus

    # Vendula Poncova: python3-nose-testconfig and python3-rpmfluff were
    # pulled in as test dependencies of anaconda, they shouldn't be needed
    - python3-nose-testconfig
    - python3-rpmfluff

    # Vendula Poncova: python3-ordered-set and python3-ntplib were pulled in
    # as dependencies of anaconda and pykickstart, they shouldn't be needed
    - python3-ordered-set
    - python3-ntplib
