document: feedback-pipeline-workload
version: 1
data:
  name: Kerberos Server
  description: Stand-alone Kerberos server
  maintainer: sst_identity_management

  packages:
  - krb5-server

  labels:
  - eln
  - c9s
