document: feedback-pipeline-unwanted
version: 1
data:
  name: Unwanted Debuggers packages
  description: Unwanted Debuggers packages
  maintainer: sst_platform_tools

  unwanted_packages:
  - babeltrace
  - gdb-minimal

  labels:
  - eln
  - c9s
