document: feedback-pipeline-workload
version: 1
data:
  name: Virtualization on RHEL - KVM Userspace
  description: Userspace agents and tools that enable virtualization capabilities on RHEL
  maintainer: sst_virtualization

  packages:
  - augeas
  - dtc
  - gtk-vnc2
  - guestfs-tools
  - hexedit
  - hivex
  - ipxe-roms-qemu
  - libguestfs
  - libguestfs-inspect-icons
  - libiscsi
  - libnbd
  - libosinfo
  - libvirt
  - libvirt-dbus
  - libvirt-glib
  - mdevctl
  - nbdkit
  - osinfo-db
  - osinfo-db-tools
  - python-augeas
  - python3-libvirt
  - seabios
  - sgabios
  - spice-protocol
  - spice-vdagent
  - supermin
  - vhostmd
  - virt-install
  - virt-top
  - virt-viewer
  - virt-what

  labels:
  - c9s

  arch_packages:
    x86_64:
    - edk2-ovmf
    - libguestfs-winsupport
    - libpmem
    - qemu-kvm
    - sevctl
    - virt-p2v
    - virt-v2v
    ppc64le:
    - libpmem
    - powerpc-utils
    aarch64:
    - edk2-aarch64
    - qemu-kvm
    s390x:
    - qemu-kvm
