document: feedback-pipeline-workload
version: 1
data:
  name: HTTP Servers - NGINX
  description: CS Infrastructure Services - NGINX
  maintainer: sst_cs_infra_services

  packages:
  - nginx
  - nginx-all-modules

  modules_enable:
  - nginx:1.18
  
  labels:
  - eln
