document: feedback-pipeline-workload
version: 1
data:
  name: FreeRADIUS Server
  description: An open source implementation of RADIUS, the IETF protocol for AAA (Authorisation, Authentication, and Accounting).
  maintainer: sst_identity_management

  packages:
  - freeradius

  labels:
  - eln
  - c9s
