document: feedback-pipeline-workload
version: 1
data:
  name: HTTP Servers - Varnish Cache
  description: CS Infrastructure Services - Varnish Cache
  maintainer: sst_cs_infra_services

  packages:
  - varnish
  - varnish-modules
  - varnish-docs
  - varnish-devel

  # asamalik: there are no modules yet, so commenting this part out
  # this way we won't lose the packages from the set
  #modules_enable:
  #- varnish:6.0
  
  labels:
  - c9s
