document: feedback-pipeline-workload
version: 1
data:
  name: FreeIPA Client - minimal
  description: FreeIPA client
  maintainer: sst_identity_management

  packages:
  - ipa-client
  - ipa-selinux # rich dependency that is otherwise unmet

  labels:
  - eln
  - c9s
