document: feedback-pipeline-workload
version: 1
data:
  name: Python parsers
  description: Python packages for parsing common data formats
  maintainer: sst_cs_apps

  packages:
  - python3-lxml
  - python3-pyyaml
  - python3-toml

  labels:
  - eln
  - c9s
