document: feedback-pipeline-workload
version: 1
data:
  name: FreeIPA Server - Full
  description: FreeIPA Server - all modules
  maintainer: sst_identity_management

  packages:
  - ipa-server
  - ipa-server-trust-ad
  - ipa-server-dns
  - ipa-healthcheck
  - ipa-selinux # rich dependency that is otherwise unmet

  labels:
  - eln
  - c9s
