document: feedback-pipeline-workload
version: 1
data:
  name: XDP
  description: Tools to support XDP
  maintainer: sst_kernel_tps

  packages:
  - xdp-tools
  - libxdp
  - libxdp-devel
  - libxdp-static
  labels:
  - eln
  - c9s
