document: feedback-pipeline-workload
version: 1
data:
  name: edge packages
  description: Packages for edge usecases
  maintainer: sst_edge

  packages:
  - can-utils
  - greenboot
  - greenboot-reboot
  - greenboot-status
  - ignition
  - libgpiod-devel
  - libgpiod-utils
  - python3-libgpiod
  - libi2cd-devel
  - libiio-devel
  - libiio-utils
  - python3-iio
  - ostree
  - rpm-ostree
  - nss-altfiles
  - coreos-installer

  arch_packages:
    x86_64:
    - greenboot-grub2
    - greenboot-rpm-ostree-grub2
    ppc64le:
    - greenboot-grub2
    - greenboot-rpm-ostree-grub2
    aarch64:
    - greenboot-grub2
    - greenboot-rpm-ostree-grub2

  labels:
  - eln
  - c9s

