document: feedback-pipeline-workload
version: 1
data:
  name: libsmbios
  description: Libsmbios C/C++ shared libraries
  maintainer: sst_desktop

  packages: []

  labels:
  - eln
  - c9s

  arch_packages:
    x86_64:
      - libsmbios
