document: feedback-pipeline-workload
version: 1
data:
  name: Mozilla Thunderbird
  description: Default e-mail client for Workstation
  maintainer: sst_desktop_applications

  packages:
  - thunderbird

  labels:
  - eln
  - c9s
