document: feedback-pipeline-workload
version: 1
data:
  name: Packages for mailx functionality
  description: S-nail packages replaces functionality of mailx
  maintainer: sst_cs_apps

  packages:
  - s-nail

  labels:
  - eln
  - c9s
