document: feedback-pipeline-workload
version: 1
data:
  name: Anaconda
  description: Graphical system installer
  maintainer: sst_front_door
  labels:
    - eln
    - c9s

  packages:
    - anaconda
