document: feedback-pipeline-workload
version: 1
data:
  name: tzdata
  description: The latest time zone database as released by IANA.
  maintainer: james

  packages:
  - tzdata
  - tzdata-java

  labels:
  - centos
