document: feedback-pipeline-workload
version: 1
data:
  name: HTTP Servers - Apache httpd
  description: CentOS Stream - Apache HTTP Server
  maintainer: james

  modules_enable:
  - httpd:2.4

  packages:
  - httpd
  - httpd-tools
  - httpd-filesystem
  - mod_ssl
  - mod_proxy_html
  - mod_ldap
  - mod_session
  - python3-mod_wsgi
  - httpd-devel
  - httpd-manual
  - mod_http2
  - mod_md
  - mod_fcgid
  - mod_security
  - mod_security-mlogc
  - mod_security_crs
  - apr
  - apr-devel
  - apr-util
  - apr-util-devel
  - apr-util-ldap
  - apr-util-mysql
  - apr-util-openssl
  - apr-util-sqlite
  - apr-util-pgsql
  - apr-util-odbc

  labels:
  - centos
