---
document: feedback-pipeline-compose-view
version: 1
data:
  name: Adam's experimental c9s view
  description: Adam's experimental c9s view
  maintainer: asamalik
  labels:
  - c9s
  repository: repository-c9s

  buildroot_strategy: dep_tracker