---
document: feedback-pipeline-compose-view
version: 1
data:
  name: Adam's experimental ELN view
  description: Adam's experimental ELN view
  maintainer: asamalik
  labels:
  - eln
  repository: repository-fedora-eln
  buildroot_strategy: root_logs